### ISSUE TITLE
Code fails to compile on macOS 12.4

### ISSUE THREAD

**Issue by agatti** [grumpycoders/pcsx-redux#977]
### Describe the bug

The code fails to compile with this error:

```bash
c++ `pkg-config --cflags capstone freetype2 glfw3 libavcodec libavformat libavutil libswresample libuv zlib libcurl` -I. -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/gl3w -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/backends -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/http-parser -Ithird_party/libelfin -Ithird_party/luajit/src -Ithird_party/luv/src -Ithird_party/luv/deps/lua-compat-5.3/c-api -Ithird_party/md4c/src -Ithird_party/ucl -Ithird_party/ucl/include -Ithird_party/zep/extensions -Ithird_party/zep/include -Ithird_party/xbyak/xbyak -g -DIMGUI_IMPL_OPENGL_LOADER_GL3W -DIMGUI_ENABLE_FREETYPE -DZEP_FEATURE_CPP_FILE_SYSTEM -mmacosx-version-min=10.15 -stdlib=libc++ -O3 -pthread -DVIXL_INCLUDE_TARGET_AARCH64 -DVIXL_CODE_BUFFER_MMAP -Ithird_party/vixl/src -Ithird_party/vixl/src/aarch64  -std=c++2a -fcoroutines-ts -M -MT src/gui/widgets/dynarec_disassembly.o -MF src/gui/widgets/dynarec_disassembly.dep src/gui/widgets/dynarec_disassembly.cc
src/gui/widgets/dynarec_disassembly.cc:22:10: fatal error: 'capstone/capstone.h' file not found
#include <capstone/capstone.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** No rule to make target `src/gui/widgets/dynarec_disassembly.dep', needed by `dep'.  Stop.
```

### Expected behavior

The code compiles.

### Steps to reproduce the bug

1. Install the necessary dependencies with `install-brew-depend
encies.sh`
2. Launch `make`

### Operating System

macOS 12.4

### PCSX-Redux version

Current HEAD (b0be0e871bcaa6f9612f5e740ff75cdec0a7979d)

### CPU model

m1

### GPU model

N/A

### BIOS version

N/A

### CPU emulation mode

Interpreter

### Additional information

On my system using Capstone 4.0.2 installed via homebrew, `pkg-config --cflags capstone` returns `-I/opt/homebrew/Cellar/capstone/4.0.2/include/capstone`, which means `#include <capstone/capstone.h>` should be `#include <capstone.h>` in `src/gui/widgets/dynarec_disassembly.cc`.
