### ISSUE TITLE
aur-build red on main since #2106: the AUR package has a hand-maintained submodule list and does not know about iec-60908b or cueparser

### ISSUE THREAD

**Issue by rixnobis** [grumpycoders/pcsx-redux#2111]
`aur-build` has been failing on `main` since `0c5dc607` (2026-09-19T05:51Z), three runs in a row. Last green was `d1bc093f`. This is my regression from #2106.

```
src/cdrom/cdriso-cue.cc:22:10: fatal error: cueparser/cueparser.h: No such file or directory
src/cdrom/file.cc:25:10: fatal error: iec-60908b/edcecc.h: No such file or directory
make: *** No rule to make target 'deps/Release/src/cdrom/cdriso-cue.dep', needed by 'dep'.
```

#2106 turned `iec-60908b` and `cueparser` into submodules. `91e2661a` updated the Nix build for it. The AUR package needs the same update and lives outside this repo. `pcsx-redux-git` in the AUR maintains its submodule set by hand in three places (`source=()`, the `git config submodule.*.url` block, and the `git submodule update` argument list), and neither new name appears in any of them. The CI job clones that package from the AUR and only rewrites the upstream source line, so it inherits the stale list.

The two additions needed there are `git+https://github.com/rixnobis/iec-60908b.git` and `git+https://github.com/rixnobis/cueparser.git`, each with a matching `git config submodule.third_party/<name>.url "$srcdir/<name>"` and an entry in the `submodule update` list.

I could make CI green by patching the two submodules in from the workflow after the existing `sed`. That leaves anyone building `pcsx-redux-git` from the AUR hitting the same failure with nothing pointing at it, so I have not done it. Say the word if you want the workflow patch anyway, or if you want me to take it to the AUR maintainer.

**Comment by Algebro7** [comment]
Thanks @rixnobis , I've updated the AUR package to pull in these submodules and removed the now-unused ones (uC-sdk and psxlua). This should be fixed.

**Comment by rixnobis** [comment]
Green as of 2026-09-22T06:53:27Z, run 35696897334 on `911271b7`. Thanks @Algebro7.

Closing. Same shape and same turnaround as the miniaudio break after the SDL3 migration, so the pattern holds: the PKGBUILD hand-maintains the submodule list, a submodule change here breaks it, and the fix lands on the AUR side within a day or two.
